---------------------------------------------------------------------
-- conky-modern theme
-- Author: jamerst
-- Github: https://github.com/jamerst/conky-modern
-- Based on:
--		* https://github.com/Dacha204/conky-spoclo
---------------------------------------------------------------------

conky.config = {

	background = true,
	update_interval = 1,

	double_buffer = true,
	no_buffers = true,
	text_buffer_size = 2048,

	alignment = 'top_right',
	gap_x = 25,
	gap_y = 50,

	short_units = true,

	minimum_height = 15,
	minimum_width = 200,
	maximum_width = 220,

	own_window = true,
	own_window_type = 'desktop',
	own_window_argb_visual = true,
	own_window_argb_value = 100,
	own_window_transparent = false,

	own_window_class = 'conky-semi',
	own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
	border_inner_margin = 10,
	border_outer_margin = 1,

	draw_shades = false,
	draw_outline = false,
	draw_borders = false,
	draw_graph_borders = true,

	override_utf8_locale = true,
	use_xft = true,
	font = 'Adwaita Sans:size=9',
	uppercase = false,
	imlib_cache_size = 0,

	default_color = '#FFFFFF',
	shade_color = '#000000',
	background_color = '#000000',
	
};

conky.text = [[

${font Adwaita Sans:size=14:style=Bold}${alignc}${time %A – %D} ${font Adwaita Sans:size=8}
${hr 2}
${distribution} ${alignr} ${color FFFFFF} ${kernel}
Uptime: ${uptime}

${font Adwaita Sans:size=11:style=Bold}CPU ${hr 1} ${font Adwaita Sans:size=8}
${voffset 5}${color FFFFFF} CPU: ${cpu}% ${alignr}${freq} Mhz
${cpugraph FFFFFF FFFFFF} 
${top name 1}$alignr${top cpu 1}
${top name 2}$alignr${top cpu 2}
${top name 3}$alignr${top cpu 3}

${font Adwaita Sans:size=11:style=Bold}MEMORY ${hr 1} ${font Adwaita Sans:size=8}
${voffset 5}RAM: ${color FFFFFF}$memperc% ${alignr} ${mem} / ${memmax} 
${membar 8}
${top_mem name 1}$alignr${top_mem mem 1}
${top_mem name 2}$alignr${top_mem mem 2}
${top_mem name 3}$alignr${top_mem mem 3}

SWAP: ${color FFFFFF}$swapperc% ${alignr} ${swap} / ${swapmax} 
${swapbar 8}

${font Adwaita Sans:size=11:style=Bold}FILESYSTEM ${hr 1} ${font Adwaita Sans:size=8}
${voffset 5}ROOT:  ${color FFFFFF}${fs_used_perc /}% ${alignr} ${fs_used /} / ${fs_size /} 
${fs_bar }

${font Adwaita Sans:size=11:style=Bold}BATTERY ${hr 1} ${font Adwaita Sans:size=8}
${voffset 5}${battery} ${alignr} ${battery_time}
${battery_bar 8}

]];
