#!/usr/bin/env bash
set -e

## VARIABLES
LightDMBack="Autumn Countryside Landscape.png"

source nl-xfce

installXorg (){
	echo "## Instalando o Xorg"
	sleep 1
	sudo pacman -Syu --noconfirm --needed xorg
}

installXFCE () {
	echo "## Instalando o Desktop Básico"
	sleep 1
	sudo pacman -Syu --noconfirm --needed xfce4-appfinder xfce4-panel xfce4-session xfce4-settings xfconf xfdesktop xfwm4 xfce4-terminal thunar exo xfce4-screensaver gvfs lightdm lightdm-gtk-greeter xfce4-screensaver xfce4-terminal sound-theme-freedesktop rofi
}

installApps () {
	echo "## Instalando Pacotes Extras do XFCE"
	sleep 1
	sudo pacman -Syu --noconfirm --needed xfce4-power-manager xfce4-pulseaudio-plugin xfce4-screenshooter xfce4-notifyd network-manager-applet papirus-icon-theme adwaita-fonts
	
	echo "## Instalando Programas"
	sleep 1
	sudo pacman -Syu --noconfirm --needed firefox fastfetch alacritty mpv ristretto geany xarchiver htop conky unzip zip
	
	echo "## Instalando Suporte ao Scanner e Impressoras"
	sleep 1
	sudo pacman -Syu --noconfirm --needed cups sane 
	
	echo "## Instalando Componentes do Desktop"
	sleep 1
	sudo pacman -Syu --noconfirm --needed xdg-user-dirs-gtk pulseaudio pulseaudio-alsa networkmanager acpi polkit-gnome udisks2 blueman bluez pavucontrol tlp upower
	
	echo "## Instalando Dependências dos Scripts"
	sleep 1
	sudo pacman -Syu --noconfirm --needed libpulse xclip brightnessctl ffmpeg clipnotify
	
	echo "## Instalando Pacotes Extras do Thunar"
	sleep 1
	sudo pacman -Syu --noconfirm --needed thunar-volman tumbler thunar-media-tags-plugin thunar-archive-plugin
	
	echo "## Instalando o Suporte a Flatpaks"
	sleep 1
	sudo pacman -Syu --noconfirm --needed flatpak
}

enableServices () {
	sleep 1
	
	echo "## Ativando o LightDM"
	
	sudo systemctl enable lightdm	
		
	echo "## Ativando o Bluetooth"
	sudo systemctl enable bluetooth
	
	echo "## Ativando o CUPS"
	sudo systemctl enable cups
}

rebootNL () {
	for sec in `seq 5 -1 1`; do
			echo "## Reiniciando em $sec segundos"
			sleep 1
	done
	sudo reboot
}

installXorg
installXFCE
installFonts
installApps
doConfigs
userConfigs
configLightDM
enableServices
rebootNL
