#!/usr/bin/env bash

echo "## Ativando o Repositório Comunitário"
setup-apkrepos -c -f

echo "## Instalando o Xorg"
sleep 1
apk add xorg-server xf86-input-libinput xinit eudev mesa-dri-gallium

echo "## Instalando o Desktop"
sleep 1
apk add xfce4 firefox elogind gvfs lightdm lightdm-gtk-greeter polkit-elogind xfce4-screensaver xfce4-terminal font-dejavu

echo "## Instalando outros Programas"
sleep
apk add fastfetch alacritty flatpak mpv ristretto geany xarchiver htop conky xfce4-power-manager xdg-user-dirs pulseaudio network-manager-applet cups sane zathura thunar-volman thunar-media-tags-plugin thunar-archive-plugin networkmanager acpi xfce-polkit unzip zip conky papirus-icon-theme udisks2 blueman bluez xfce4-pulseaudio-plugin pavucontrol xfce4-screenshooter gtk-murrine-engine sound-theme-freedesktop pulseaudio-utils xfce4-notifyd xclip brightnessctl tlp

echo "## Ativando o LightDM"
sleep 1
rc-update add lightdm

echo "## Ativando o Dbus"
rc-update add dbus

echo "## Ativando o Network Manager"
rc-update add networkmanager

echo "## Ativando o TLP"
rc-update add tlp

