#!/usr/bin/env bash

## Variables
APKREPOS_PATH="${ROOT}"etc/apk/repositories

fastestMirror() {
	local url=
	local arch="$(apk --print-arch)"
	for url in $MIRRORS; do
		# warm up the dns cache
		$MOCK nslookup $(get_hostname_from_url $url) >/dev/null 2>&1
		local time="$(time_cmd wget --spider -q -T 5 -t 1 \
			${url%/}/edge/main/$arch/APKINDEX.tar.gz)"
		if [ -n "$time" ]; then
			echo "$time $url"
		fi
	done | tee /dev/stderr | sort -nk1,1 | head -n1 | cut -d' ' -f2
}

communityRepo () {
	for repo in $(grep '^[^#].*/main$' "$APKREPOS_PATH" 2>/dev/null); do
		crepo="${repo%%/main}/community"
		if ! grep -qx -- "$crepo" "$APKREPOS_PATH"; then
			echo ">>> Enabling repository $crepo"
			echo "$crepo" >> "$APKREPOS_PATH"
		fi
	done
	
	echo "Finding fastest mirror... "
	local fastest="$(fastestMirror)"
	if [ -z "$fastest" ]; then
		echo "Warning! No mirror found" >&2
		return 1
	fi
	add_mirror "$fastest"
	
	apk update --quiet $apk_root_opt && echo "done."
}
