#!/usr/bin/env bash
set -e

## VARIABLES
LightDMBack="Autumn Countryside Landscape.png"

source nl-xfce

installXorg (){
	echo "## Instalando o Xorg"
	sleep 1
	sudo xbps-install -y xorg-server xf86-input-libinput xinit mesa-libgallium mesa-dri
}

installXFCE () {
	echo "## Instalando o Desktop Básico"
	sleep 1
	sudo xbps-install -y xfce4-appfinder xfce4-panel xfce4-session xfce4-settings xfconf xfdesktop xfwm4 xfce4-terminal Thunar exo xfce4-screensaver elogind gvfs lightdm lightdm-gtk-greeter xfce4-screensaver xfce4-terminal sound-theme-freedesktop 
}

installApps () {
	echo "## Instalando Pacotes Extras do XFCE"
	sleep 1
	sudo xbps-install -y xfce4-power-manager xfce4-pulseaudio-plugin xfce4-screenshooter xfce4-notifyd network-manager-applet papirus-icon-theme gtk-engine-murrine
	
	echo "## Instalando Programas"
	sleep 1
	sudo xbps-install -y firefox fastfetch alacritty mpv ristretto geany xarchiver htop conky unzip zip
	
	echo "## Instalando Suporte ao Scanner e Impressoras"
	sleep 1
	sudo xbps-install -y cups sane 
	
	echo "## Instalando Componentes do Desktop"
	sleep 1
	sudo xbps-install -y xdg-user-dirs-gtk pulseaudio alsa-plugins-pulseaudio NetworkManager acpi xfce-polkit udisks2 blueman bluez pavucontrol tlp upower
	
	echo "## Instalando Dependências dos Scripts"
	sleep 1
	sudo xbps-install -y pulseaudio-utils xclip brightnessctl ffmpeg clipnotify
	
	echo "## Instalando Pacotes Extras do Thunar"
	sleep 1
	sudo xbps-install -y thunar-volman tumbler thunar-media-tags-plugin thunar-archive-plugin
	
	echo "## Instalando o Suporte a Flatpaks"
	sleep 1
	sudo xbps-install -y flatpak
}

enableServices () {
	sleep 1
	
	echo "## Ativando o LightDM"
	sudo ln -s /etc/sv/lightdm /var/service/
	
	echo "## Ativando o Dbus"
	sudo ln -s /etc/sv/dbus /var/service/
	
	if [[ -f "/var/service/dhcpcd" ]]; then
		echo "## Desativando o DHCPCD"
		sudo rm /var/service/dhcpcd
	fi
	
	if [[ -f "/var/service/wpa_supplicant" ]]; then
		echo "## Desativando o WPA Supplicant"
		sudo rm /var/service/wpa_supplicant
	fi
	
	echo "## Ativando o Network Manager"
	sudo ln -s /etc/sv/NetworkManager /var/service/
	
	echo "## Ativando o TLP"
	sudo ln -s /etc/sv/tlp /var/service/
	
	echo "## Ativando o Bluetooth"
	sudo ln -s /etc/sv/bluetoothd /var/service/	
	
	echo "## Ativando o CUPS"
	sudo ln -s /etc/sv/cupsd /var/service/
}

rebootNL () {
	for sec in `seq 5 -1 1`; do
			echo "## Reiniciando em $sec segundos"
			sleep 1
	done
	sudo reboot
}

installXorg
installXFCE
installFonts
installApps
doConfigs
userConfigs
configLightDM
enableServices
rebootNL
