#!/usr/bin/env bash
set -e

## VARIABLES
LightDMBack="Autumn Countryside Landscape.png"

superCmd () {
	if ! [ "$(id -u)" == "0" ]; then
		if ! [ -z "$(command -v sudo)" ]; then
			superUser="sudo"
		elif ! [ -z "$(command -v doas)" ]; then
			superUser="doas"
		fi
	fi
}

checkFolders () {
	echo -e "\n## Verificando Diretórios..."
	
	if ! [ -d /usr/share/fonts ]; then
		${superUser} mkdir -p /usr/share/fonts
	fi
	
	if ! [ -d /etc/skel/.config ]; then
		${superUser} mkdir -p /etc/skel/.config
	fi
}

installFonts () {
	echo -e "\n## Instalando as Fontes..."
	${superUser} cp fonts/* /usr/share/fonts
	${superUser} fc-cache -fv
}

doConfigs () {
	sleep 1
	echo "## Copiando Wallpapers"
	${superUser} cp backgrounds/* /usr/share/backgrounds
	
	echo "## Copiando Scripts"
	chmod +x scripts/*
	${superUser} cp scripts/* /usr/local/bin
	
	echo "## Copiando Configurações"
	${superUser} cp -r config/* /etc/skel/.config
		
	echo "## Instalando Temas..."
	tar -xzvf themes.tar.gz
	${superUser} cp -r themes/* /usr/share/themes/
}

sysConfigs () {
	echo "## Copiando Configurações nas Pastas dos Usuários"
	for d in /home/*; do 
		if ! [ -d  "$d"/.config ]; then
			${superUser} mkdir "$d"/.config
		fi
		
		${superUser} cp -r config/* "$d"/.config		
	done
}

userConfigs () {
	echo "## Copiando Configurações para a Pasta do Usuário"
	if ! [ -d  $HOME/.config ]; then
			mkdir $HOME/.config
	fi
	cp -r config/* $HOME/.config
	xfconf-query -c xsettings -p /Net/IconThemeName -s "Papirus-Dark"
}

configLightDM (){
	echo "## Configurando o LightDM"
	sleep 1
	${superUser} cp "/usr/share/backgrounds/$LightDMBack" /usr/share/pixmaps
	${superUser} mv "/usr/share/pixmaps/$LightDMBack" "/usr/share/pixmaps/background.png"
	${superUser} sed -i 's|^#\(background=.*\)|\1|' /etc/lightdm/lightdm-gtk-greeter.conf
	${superUser} sed -i 's|^background=.*|background=/usr/share/pixmaps/background.png|' /etc/lightdm/lightdm-gtk-greeter.conf
	${superUser} sed -i 's|^#\(icon-theme-name=.*\)|\1|' /etc/lightdm/lightdm-gtk-greeter.conf
	${superUser} sed -i 's|^icon-theme-name=.*|icon-theme-name=Papirus-Dark|' /etc/lightdm/lightdm-gtk-greeter.conf
}

superCmd
checkFolders
